### ISSUE TITLE
Pitanje

### ISSUE THREAD

**Issue by TornjV** [ViktorKatz/PsychoJigglypuff#14]
Mене занима да ми ви мене кажете где има јефтина кавурма, чварци, мене то брине

**Comment by ViktorKatz** [comment]
Wtf otkud ti permission da praviš issue?

**Comment by TornjV** [comment]
![image](https://user-images.githubusercontent.com/13820300/120019322-98189d80-bfe8-11eb-84bb-5ca8e39ce13c.jpeg)
